env:
  browser: true
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - plugin:import/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaVersion: 12
rules:
  no-extra-bind: error
  no-implicit-globals: error
  no-var: error
  prefer-const: error

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - airbnb-typescript
      - plugin:import/typescript
      - 'plugin:react/recommended'
      - 'plugin:@typescript-eslint/recommended'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
      sourceType: module
      ecmaFeatures:
        jsx: true
    plugins:
      - react
      - '@typescript-eslint'
      - react-hooks
    rules:
      react/no-unknown-property: [error, { ignore: [class] }]
      # Checks rules of Hooks
      react-hooks/rules-of-hooks: error
      # Checks effect dependencies
      react-hooks/exhaustive-deps: warn
      no-restricted-imports:
        - error
        - name: moment
          message: Please use date-fns instead.
        - name: moment-timezone
          message: Please use date-fns instead.
      import/no-extraneous-dependencies: off
      jsx-a11y/alt-text: off
      jsx-a11y/anchor-is-valid: off
      jsx-a11y/click-events-have-key-events: off
      jsx-a11y/no-static-element-interactions: off
      import/no-unresolved: "error"
      react/prop-types: "off" # Since we do not use prop-types. We use typescript.
      react/require-default-props: "off" # Since we do not use prop-types. We use typescript.
    settings:
      react:
        # If this line cause problem in future. Check https://github.com/yannickcr/eslint-plugin-react/issues/1955
        version: 'latest'
      import/parsers:
        "@typescript-eslint/parser":
          - ".ts"
          - ".tsx"
      import/resolver:
        typescript:
          - alwaysTryTypes: true
